name: vpn
description: Go back home vpn

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_inappwebview: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
    - android_asset/dashboard/
    - android_asset/dashboard/css/app.30808ca4.css
    - android_asset/dashboard/css/chunk-4bb5976f.358eaf0e.css
    - android_asset/dashboard/css/chunk-63f34120.47a7fe86.css
    - android_asset/dashboard/css/chunk-70a4f67c.115dd09a.css
    - android_asset/dashboard/css/chunk-157bdbad.b8c22865.css
    - android_asset/dashboard/css/chunk-76680e5c.304ee797.css
    - android_asset/dashboard/css/chunk-78449fe4.176f0114.css
    - android_asset/dashboard/css/chunk-vendors.1cf0be08.css
    - android_asset/dashboard/img/login.5951d7c0.png
    - android_asset/dashboard/img/timg.4bff593f.jpeg
    - android_asset/dashboard/js/app.c37ccb5f.js
    - android_asset/dashboard/js/chunk-2d0c4873.ceb3553a.js
    - android_asset/dashboard/js/chunk-2d2178fa.b68353cd.js
    - android_asset/dashboard/js/chunk-4bb5976f.376a1bdc.js
    - android_asset/dashboard/js/chunk-63f34120.31a438d1.js
    - android_asset/dashboard/js/chunk-70a4f67c.c8ee13b9.js
    - android_asset/dashboard/js/chunk-157bdbad.7933e780.js
    - android_asset/dashboard/js/chunk-76680e5c.c0624d3e.js
    - android_asset/dashboard/js/chunk-78449fe4.19f02c92.js
    - android_asset/dashboard/js/chunk-vendors.5e807e09.js
    - android_asset/dashboard/js/hello.js
    - android_asset/dashboard/hello.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
